### ISSUE TITLE
Leave a comment

### ISSUE THREAD

**Issue by agoalofalife** [social-manager-tools/instagram-bot.js#12]
are there any plans to post a comment under a photo?
it can help to increase subscribers!

**Comment by ptkdev** [comment]
Next feature is follow-defollow algorithm (release v0.7.0, end of march 2018). When it is stable next release is comments (release v0.8.0, middle april 2018)

**Comment by agoalofalife** [comment]
well, maybe I can do something to help
if what we are going to discuss it here(github)
I think , you can improve the interface modes
but in the future

**Comment by ptkdev** [comment]
For help in development:
1. duplicate modules (example: copy `/modules/likemode_classic.js` and rename in `/modules/comments_classic.js`). 
2. Edit module, clean useless function and develop a flow. 
3. Edit bot.js and add `comments_classic` in `switch()`
4. Add configuration array of comments in `config.js.tpl`
5. Test, if work send pull request.

**Comment by agoalofalife** [comment]
if I get a chance I will help

**Comment by agoalofalife** [comment]
@ptkdev I propose to create an interface to comments
- `comment`  as a separate scenario class
- register and add new `comment class` from client code
- add algorithms for commenting

it is only ideas

**Comment by ptkdev** [comment]
Ok, is good interface for me 👍
