### ISSUE TITLE
Login dont work

### ISSUE THREAD

**Issue by JaviBalado** [social-manager-tools/instagram-bot.js#124]
Hi,

Firstly sorry for my english, i’m an spanish writer.

When i use the bot, the submit button dont works. I should give manually 

Regards 

### Versions

Replace the values below with your own:

- **Bot Version:** v0.7.0
- **Node Version:** v8.9 (Bot require >= 7.6)
- **Operating System:** Ubuntu 14.04
- **Browser:** Google Chrome 64

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by JaviBalado** [comment]
I use windows

**Comment by ptkdev** [comment]
Solved 10minutes ago with new release :)

Run `npm run clean` in `instagram-bot.js` folder or download gui [social-manager-tools](https://socialmanagertools.ptkdev.io/)

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
