### ISSUE TITLE
 Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by JaviBalado** [social-manager-tools/instagram-bot.js#126]
Hi i follow the steps to install bot in my ubuntu server and ui have the following fail:
```
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
[INFO] utils: Bot is updated! :D
(node:27237) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/instagram-bot.js-master/node_modules/puppeteer/lib/Launcher.js:285:14)
    at ChildProcess.helper.addEventListener (/root/instagram-bot.js-master/node_modules/puppeteer/lib/Launcher.js:275:60)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
(node:27237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27237) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

why?
### Versions

Replace the values below with your own:

- **Bot Version:** the last version
- **Node Version:** v10.11.0 (Bot require >= 7.6)
- **Operating System:** Ubuntu 16.04
- **Browser:** Google Chrome 64

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Please provide config.js (without password) or `executable_path`

**Comment by JaviBalado** [comment]
// InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "user", // without @
    "instagram_password": "pas",
    "instagram_hashtag": ["gato", "gatito", "gatos"], //without #, raccomanded more than 20
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.

is this,i dont see executable_path

**Comment by ptkdev** [comment]
If you isn't nerd or developer please use [Social Manger Tools](https://socialmanagertools.ptkdev.io/)

**Comment by JaviBalado** [comment]
I am informatic student and i ask because i want learn

**Comment by ptkdev** [comment]
This error happen when:
1. Puppeter is not installed, solution: try `npm run clean`
2. `executable_path` have bad value, solution: try set to `""` (empty value) or set to `/usr/bin/chromium`

This parameter exist in `config.js`, please look more carefully before open issue

**Comment by JaviBalado** [comment]
Hello, first of all thank you very much for and apologize if I ask you newbie questions. This year I have started to study computer engineering and I want to move forward as fast as possible, I plan to take it well but servants have it worse besides having the handicap of English.

I've been testing all afternoon and I have a new failure. I tried to enter the path you gave me and leave it blank and I gave an error. later, I introduced a `whereis google-chrome` and it gave me the following route: "/usr/share/man/man1/google-chrome.1.gz" I used it and it stopped giving me chrome failures but it gave me the following failure of which I can not find a solution:
`
[INFO] utils: loginpin.txt exist
[INFO] utils: logs/debug.log exist
[INFO] utils: logs/errors.log exist
[INFO] utils: databases/fdf.db exist
[INFO] utils: databases/logs.db exist
[WARNING] utils: Bot work? Please donate for support this project!
[WARNING] utils: Donate with patreon: http://patreon.ptkdev.io
[WARNING] utils: Donate with paypal: http://paypal.ptkdev.io
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/share/man/man1/google-chrome.1.gz EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`
I try to change permissions, etc. and it doesn´t work.
Thank you so much

**Comment by ptkdev** [comment]
google-chrome is installed? Imho no...
1. Download [latest bot version](https://github.com/social-manager-tools/instagram-bot.js/archive/master.zip) and extract it.
2. Download [Node.js](https://nodejs.org/it/) >= 7.6 and install it. On Ubuntu: `sudo apt-get install npm`
3. Run `npm install` in `instagram-bot.js-master` folder.
4. Get [config.js](https://raw.githubusercontent.com/social-manager-tools/instagram-bot-lib/master/config.js.tpl) remove  `.tpl ` suffix and insert file into `configs` folder, fill it properly.
5. Start the bot via `node bot.js --config="./configs/config.js"`
Why you change `executable_path`? Empty value is correct... If you use Ubuntu default config work

**Comment by ptkdev** [comment]
Note: on server instagram ban you. Instagram have list of cloud ip and famous hosting. Don't try use bot on server. Remember set `chromium_headless` on `true` if use Ubuntu without DE. 

...and RTFM

**Comment by JaviBalado** [comment]
i read the fucking manuall and i do all steps but the bot don't work. thank you anyway
