### ISSUE TITLE
Questions: Start in multiple modes / Error safety

### ISSUE THREAD

**Issue by lollymouth** [social-manager-tools/instagram-bot.js#127]
Hey Patryk,

Is it possible to start multiple modes at the same time? 
Is there a safety to stop the process if a certain amount of errors occur?

Cheers,

**Comment by ptkdev** [comment]
Hi!
Yep is possibile and don't is a problem. 

But if you run 2 likemode remember don't exceed limit of total 1000 like. 
Example: Set `likemode_realistic` to `700` and `likemode_superlike` to `100` = total is 1000 day 

P.s. Superlike put 3 like/user. 100*3 = 300 + 700 = 1000

**Comment by ptkdev** [comment]
`Is there a safety to stop the process if a certain amount of errors occur?`
If you go to soft ban (bot put like but instagram remove it, stop bot 24h). If you exceed day limits is raccomanded stop.

**Comment by lollymouth** [comment]
> Yep is possibile and don't is a problem.

So do you start multiple time the process with multiple configs and dbs?

**Comment by ptkdev** [comment]
Example:
```
node bot.js --config="./configs/config_ptkdev_likerealistic.js"
node bot.js --config="./configs/config_ptkdev_likesuper.js"
node bot.js --config="./configs/config_ptkdev_followdefollow.js"
```

**Comment by ptkdev** [comment]
Multi-account work in CLI version and Social Manager Tools (GUI)

**Comment by lollymouth** [comment]
@ptkdev ok thanks!! Your example is great. It may be worst it to put it in the README..

**Comment by ptkdev** [comment]
Is mentioned In readme, "Parameters" chapter

**Comment by ptkdev** [comment]
Yes, you are right. If you want update and send me pull request :)
