### ISSUE TITLE
Freezing after "[INFO] utils: databases/logs.db exist"

### ISSUE THREAD

**Issue by olaims** [social-manager-tools/instagram-bot.js#129]
### Versions

Replace the values below with your own:

- Bot Version:** v0.7.0
- Node Version:** v8.9 (Bot require >= 7.6)
- Operating System: Raspbian 8
- Browser: Chromium

### Expected Behavior

Start the bot when executing node bot.js --config="./configs/config.js"

### Actual Behavior

After following all the steps from the guide https://github.com/social-manager-tools/instagram-bot.js/blob/master/INSTALL.md#setup---raspbian-8 and executing 
`node bot.js --config="./configs/config.js"`
It starts until the /logs.db file, when it get freezes and doesn't display anything (logs are also empty, not running)

### Steps to Reproduce

Just starting the bot after following these steps https://github.com/social-manager-tools/instagram-bot.js/blob/master/INSTALL.md#setup---raspbian-8

### config.js (remember to remove password)

module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "asdfasdfasdf", // without @
    "instagram_password": "asdfasdf_password",
    "instagram_hashtag": ["asdf", "sadf", "asdf"], //without #, raccomanded more than 20
    "instagram_pin": "email", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 542,      // work only in likemode_classic
    "bot_likeday_max": 785,      // work only in likemode_classic. In 2018 limit instagram is 1000/day
    "bot_sleep_night": true,    // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 0,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 0,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
    "bot_userwhitelist": ["user1", "user2", "user3"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["comment1", "comment2", "comment3"],
        }
    },
    "likemode_competitor_users": {
        "account": "asdfasdfasdf" // without @
    },

    // Puppeteer Configs
    "chrome_headless": false,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1024x768"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Hi!
## Solution 1
You need set `chrome_headless` on `true` is mandatory on raspbian. 

# Raspbian 8 is too old
Raspbian 8 is very old, i don't test this device and chromium v69 freeze random. 

## Solution 2
Try Docker with armv7 flag.
