### ISSUE TITLE
it tries to follow accounts with no posts

### ISSUE THREAD

**Issue by mrbm** [social-manager-tools/instagram-bot.js#136]
watching it work, and its following and then attempting to find a photo on an account with 0 posts.

Probably should add some logic to check to see if the account has any posts before attempting to follow it...

**Comment by ptkdev** [comment]
If account have no-post, bot try follow or like but not work and skip it.

NOTE: Please use default issue-templates with bot version, mode versiona and other info. Don't delete issue template.
