### ISSUE TITLE
[Feature request] Emoji support

### ISSUE THREAD

**Issue by Archon-** [social-manager-tools/instagram-bot.js#139]
Commend mode is very usefull however it doesn't have much value without emoji support. Seems like [this ](https://www.npmjs.com/package/node-emoji) library could be useful. Especially "emojify" mode when we use emoji id in the comment like that for instance: `I like it :wink:`.  I'm happy to provide PR if you guys think it's useful.

**Comment by ptkdev** [comment]
Emoji is supported, not work :emoji_name: but work with ascii code 👹
Copy and paste from https://www.emojifree.it or similar site.

**Comment by ptkdev** [comment]
P.s. if you want implement emoji with syntax :emoji: send pull rquest :)

**Comment by Archon-** [comment]
Well, honestly I don't care about `:emoji:` syntax but copy/pasted emoji doesn't work for me (bot empty write empty rectangle instead of emoji). But as I investigated problem emojis are supported since Puppeteer 1.7.0 and I have to use bot with older Puppeteer as I use bot on ARM-based machine. Anyway, it's OK.  :)
