### ISSUE TITLE
[INFO] twofa: yes, instagram require security pin... You can not pass!!! (cit.)

### ISSUE THREAD

**Issue by lennoox** [social-manager-tools/instagram-bot.js#140]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.7.0
- **Node Version:** v8.9 (Bot require >= 7.6)
- **Operating System:** Debian Jessie
- **Browser:** Google Chrome 64

### Actual Behavior

Everytime i start the bot (over lib or bot.js) i got the twofa. The Instagram Account (tested many different) got not pin.
[INFO] twofa: yes, instagram require security pin... You can not pass!!! (cit.)
[INFO] twofa: status location: 2
[INFO] twofa: twofa (location)
[WARNING] twofa: please insert pin in loginpin.txt or 2FA input box and wait, you have 50-60 seconds for that.. (tic... tac... tic... tac... tic...)

I used all bot modes, nothing happen.. this error appears since today. Weeks before it runs perfectly. 

### config.js (remember to remove password)
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "marcrideskidsbikes", // without @
    "instagram_password": "xxx",
    "instagram_hashtag": ["motivation", "inspiration", "zukunft", "leidenschaft", "fitlife", "vision", "teamwork", "erfolg", "lifestyle", "ziele", "träume", "hardworkpaysoff"], //without #, recommended more than 20
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [WORK] fdfmode_classic           - follow 30 users, and defollow the first followed at 31 follow (in loop). This method is not detected from socialblade. ~1h | 300/300 follow-defollow/day.
    "bot_mode": "fdfmode_classic",
    "bot_likeday_min": 800,      // work in all likemode_*
    "bot_likeday_max": 900,      // work in all likemode_*. In 2018 limit instagram is 1000/day
    "bot_sleep_night": false,    // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // number of follow-defollow user/day, work in fdfmode_classic. In 2018 limit instagram is 500/day
    "bot_followrotate": 30,      // follow 30 users, and defollow the first followed at 31 follow (in loop), work in fdfmode_classic | If is 0 defollow all followed previously by bot
    "bot_userwhitelist": [],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": [],
        }
    },
    "likemode_competitor_users": {
        "account": "Magicfox", // without @
        "account": "Sandro",
        "account": "patrick.reiser",
        "account": "juergen_hueller",
        "account": "dirkkreuter",
        "account": "mischajaniec",
    },

    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1024x768"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // DATABASES
    "fdfdatabase_path": "./databases/fdf.db", // databases with username of followed users with follodefollow mode
    "logdb_path": "./databases/logs.db",      // logs in sqllite database for better report

    // LOG
    "pin_path": "./loginpin.txt",
    "log_path": "./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path": "./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};

**Comment by ptkdev** [comment]
Hi!
Try update bot to **`v0.9.10`**, run command `npm run clean`
If 2fa not work again disabile 2fa, run bot, enable 2fa (work around)

**Comment by ptkdev** [comment]
Other info: Location 2fa issue bug happen when you use cloud, server or vps. Bot not work on server, stop after 48h because instagram ban server. 

If you use bot in pc and "location 2fa info" appear because you restart too many times. Stop bot 24h and retry after 1 days or with Phone 3g connection.

**Comment by lennoox** [comment]
Hey,

2FA is disabled and the bot still does not work. I'm using a debian vps since day 1. But yesterday the 2FA appears.. What can i do?

Lennox

**Comment by ptkdev** [comment]
`2fa error` = you have two auth enabled 

`2fa location error` = you use vps/server/cloud and instagram detect this problem and send you pin.

I try 5-6 solution but run bot on server is IMPOSSIBILE. You need buy a vps+ vpn proxy with your country. If you use ovh proxy don't work i don't know why.

Better solution is buy `Raspberry pi3` and run debian9 (raspbian) on you home connection (instagram never ban you)
