### ISSUE TITLE
Bot suddenly stopped liking posts 

### ISSUE THREAD

**Issue by tommy2049** [social-manager-tools/instagram-bot.js#141]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.7.0
- **Node Version:** v11.3 (Bot require >= 7.6)
- **Operating System:** Ubuntu 16.04
- **Browser:** Google Chrome 64

### Expected Behavior

Please describe the program's expected behavior.

```
The bot is supposed to like pics based on the hashtags given. It has been working fine for a few weeks until recently.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
The bot stopped liking pictures as of a week ago.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. clone the github repo to a working directory
2. modify the config.js script for your username and password
3. run the node command in the readme file

### config.js (remember to remove password)
```
same as default 
```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

<img width="713" alt="screen shot 2019-01-05 at 10 25 45 pm" src="https://user-images.githubusercontent.com/9774239/50731693-5c3fbd80-1139-11e9-864a-c26689af1134.png">

**Comment by ptkdev** [comment]
Hi @tommy2049 !
Try login on instagram.com, you receive same error?

**Comment by tommy2049** [comment]
Hello!

I don’t have the same error when I login on the browser, I checked my
password and everything is fine so I don’t know what the problem might be
:|.

Tom

**Comment by ptkdev** [comment]
You use bot on vps? Cloud or server?
