### ISSUE TITLE
only like realistic mode.

### ISSUE THREAD

**Issue by UN5T48L3** [social-manager-tools/instagram-bot.js#142]
When I run the bot via this command `node bot.js`
It only do "like realistic mode." Never do comment, or follow .
What is wrong?

- **Bot Version:** stable latest version
- **Node Version:** v8.9 (Bot require >= 7.6)
- **Operating System:** Debian 9
- **Browser:** Google Chrome 64

**Comment by ptkdev** [comment]
You need duplicate folder and run new session with different config. 
First folder: config with realistic_mode 
Second folder: config with comment_mode 

Run two Times the bot with different config files.

I recommanded graphic tool [Social Manager Tools](http://socialmanagertools.ptkdev.io) if you aren't Developer
