### ISSUE TITLE
Follow and Like at the same time

### ISSUE THREAD

**Issue by maximiliankleinert** [social-manager-tools/instagram-bot.js#151]
Is it possible to setup follow, like and comment at the same time?

If is not... See it as a enhancement.

Thanks in advance.

**Comment by ptkdev** [comment]
Yes, is possible: create multiple config.js files (with same user/pass but different mode) and run:
```
node bot.js --config="./configs/uaer1_like_config.js"
node bot.js --config="./configs/user1_comment_config.js"
```
