### ISSUE TITLE
 The idea to create the status of the process

### ISSUE THREAD

**Issue by agoalofalife** [social-manager-tools/instagram-bot.js#21]
I suggest for each scenario(strategy), to create the status of the process.
It is very similar to `manager state`.
**What is the status of the process?**
For example, the process can be:
- START
- FINISH
- IN PROCESS
and others
**What are the advantages in this?**
Each time to change strategy(in config file) and restart the bot not the most convenient task.
Statuses help to understand the status of the process
**Queues strategy**
We could write in the file the criteria(rule) for strategy and they can change automatically.
What do you think?
P.S. 
You can change the process(strategy) to http request.

**Comment by ptkdev** [comment]
Status of the process (start/stop/like add/follow add) are developer (in alpha) on [instagram-bot-lib](https://github.com/social-manager-tools/instagram-bot-lib) with rxjs

In future `modules` folder move to [instagram-bot-lib](https://github.com/social-manager-tools/instagram-bot-lib) npm library with rxjs event. Merge of this two repo are expected in 0.9 release, at moment no but keep it mind.

IMHO this feature is good for [gui version](https://github.com/social-manager-tools/social-manager-tools) of bot. For me is ok develop status of the process

**Comment by agoalofalife** [comment]
I never use `rxjs events`.
He gives so special?

**Comment by ptkdev** [comment]
Example: you create observable LIKE, when bot send like observable catch this. At moment is better solutions for make it easier to compose asynchronous or callback-based code.

RXJS will be integrated later so do not worry :)

**Comment by agoalofalife** [comment]
I read rxjs
Is there any example or more detailed explanation of how you plan to use it?

**Comment by agoalofalife** [comment]
I like the idea where each action is an independent component
This can be compared with components in frontend.
we can reuse this is components, examples:
- open-page
- check like photo
- check leave comment under photo
and others

**Comment by agoalofalife** [comment]
So the same file with configurations not the coolest source
For example, I would like to add comments from excel file...
I suggest this format
```js
  "comment_mode":{
        "comments":{
          "type":"array",
          "source":[],

      //   "type":"excel",
      //   "source":'path/to/file', // or url
     // .. other sources
 }
    }
```

**Comment by agoalofalife** [comment]
How can it be
![schema](http://i6.pixs.ru/storage/4/8/7/blablapng_2992383_29827487.png)

**Comment by ptkdev** [comment]
I approve this, imho is very good flow! good job bro

**Comment by agoalofalife** [comment]
@ptkdev It's like one of the options

**Comment by ptkdev** [comment]
<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>
