### ISSUE TITLE
Bot not working inside docker

### ISSUE THREAD

**Issue by augustozanellato** [social-manager-tools/instagram-bot.js#22]
### Versions

Replace the values below with your own:

- **Bot Version:** Latest (docker)
- **Node Version:** idk (docker)
- **Docker Version:** 18.03.0-ce
- **Operating System:** ArchLinux

### Expected Behavior

Please describe the program's expected behavior.

1. Launching bot in a docker container
2. Bot should start and work

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

1. Launch bot in a docker container with the command ```docker run --restart=always --name=instagram-bot -d -v config.js:/app/config.js socialmanagertools/instagram-bot.js```
2. Bot keeps restarting (log: https://pastebin.com/C194uPhB)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Launch bot in a docker container with the command ```docker run --restart=always --name=instagram-bot -d -v config.js:/app/config.js socialmanagertools/instagram-bot.js```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

### Additional Informations

The docker command provided isn't working because the Docker Hub repository name changed, the one i used should theoretically work, but it doesn't

**Comment by ptkdev** [comment]
Hi,
In docker you need `chrome_headless` on `true`. If is `false` not work in docker.

**Comment by augustozanellato** [comment]
It is already set to false

**Comment by ptkdev** [comment]
If you set on `true`, work.

**Comment by augustozanellato** [comment]
Oh sorry, I meant that it is already set to true

**Comment by augustozanellato** [comment]
Latest log:
https://pastebin.com/4Cu7rXWB
My config file:
https://pastebin.com/GrS5m0cs

**Comment by ptkdev** [comment]
Try this:
`pacman -S chromium`
and in `config.js` edit `executablePath` with this value: `/usr/bin/chromium`

**Comment by augustozanellato** [comment]
It doesn't work either, but now I think it's because the Chromium installation is inside the host system and not in the docker container
https://pastebin.com/bCG6ASLj

**Comment by augustozanellato** [comment]
Ok I think i found the bug, it doesn't work if you leave an empty executablePath, but if you put your system's chromium executable path there it works. The problem is: what do you have to put there for docker?

**Comment by ptkdev** [comment]
Ah, i found! this is bug v0.7.0 beta

Edit `bot.js` file and delete `executablePath: config.executablePath` 49 line. 
Remember to delete `,` in before line 48

**Comment by augustozanellato** [comment]
Last thing, unrelated to the issue, is there a way to cache the authentication, without to have to put the 2fa code every time?

**Comment by ptkdev** [comment]
I don't know, test it. Imho, no is valid ever.
