### ISSUE TITLE
How can I make the bot comment?

### ISSUE THREAD

**Issue by aangel031** [social-manager-tools/instagram-bot.js#29]
I successfully got the bot up and running and I was digging through the code and couldn't find anything on how to make it comment.

**Comment by ptkdev** [comment]
Hi!
Comment mode is available on [v0.7 beta version](https://github.com/social-manager-tools/instagram-bot.js/archive/master.zip). Try it.

**Comment by aangel031** [comment]
Oh okay thanks, I'll give it try later on today. Great work on this project!
