### ISSUE TITLE
[ITA] Problemi nel run del bot v0.7 (branch master) tramite docker 

### ISSUE THREAD

**Issue by Jenjo7** [social-manager-tools/instagram-bot.js#33]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.5.2
- **Node Version:** v8.9 (Bot require >= 7.6)
- **Operating System:** Ubuntu 14.04
- **Browser:** Google Chrome 64

### Expected Behavior

Please describe the program's expected behavior.

```
Probabilmente sto sbagliando io, comunque invio i dati relativi al mio problema.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Non riesco ad avviare il programma sul  container
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ho modificato il file config.js.tpl, rinominadolo in config.js e mettendo i miei dati instagram
2. l'ho avviato con questo comando: sudo docker run  -it   --restart=always     --name=instagram-bot     -d     -v /home/gianni/Documenti/Doker/insta-bot/config.js:/app/config.js    socialmanagertools/instagram-bot.js &>/dev/null
3. poi ho controllato su portainer i log (allego su screenshot) 

### config.js (remember to remove password)
```
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,

    // Instagram Account
    "instagram_username": "giannisavini", // without @
    "instagram_password": "password",
    "instagram_hashtag": ['muraleshunter', 'like4like', 'follow4follow'], //without #
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [TEST] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [TEST] fdfmode_classic           - follow user from random hashtag and defollow after 1h | 300 follow-defollow/day.
    // [TEST] comment_mode              - leave a comment under the photo via hashtag.
    // [TODO] fdfmode_defollowall       - defollow all your following (not defollow users in whitelist) | 30 defollow/hour.
    "bot_mode": "likemode_classic",
    "bot_likeday_min": 400,
    "bot_likeday_max": 600,      // in 2018 limit instagram is descreased to 400-600/day :(
    "bot_sleep_night": "7:00",   // sleep from 00:00 to 7:00 am, work only in likemode_realistic and comment_mode
    "bot_fastlike_min": "15",    // min minutes of sleep after like 10-12 photo, work only in likemode_realistic
    "bot_fastlike_max": "20",    // max minutes of sleep after like 10-12 photo, work only in likemode_realistic
    "bot_followday": 300,        // follow-defollow user/day, work only in fdfmode_classic
    "bot_userwhitelist": [''],   // usernames without @ | don't defollow this users on follow-defollow mode, work only in all fdfmode_*
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": [],
        }
    },
    "likemode_competitor_users": {
        'account': '', // without @
    },

    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ['--disable-gpu', '--no-sandbox', '--window-size=1920x1080'],
    "executablePath": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // LOG
    "log": {
        "drivers": ["console"], // slack or console
        "channels": {
            "console": '',
            "slack": {
                "webhook": ''
            }
        }
    }
};


### Screenshots (Optional)

![schermata del 2018-04-26 18-21-37](https://user-images.githubusercontent.com/26276093/39318624-e78a507c-497e-11e8-8d15-26614e070a80.png)
![schermata del 2018-04-26 18-25-55](https://user-images.githubusercontent.com/26276093/39318812-6bb915cc-497f-11e8-844c-c30a8e519396.png)

**Comment by Jenjo7** [comment]
Certo, allego il file di log e il file config.js; questo è il comando usato per runnare il container:

       sudo docker run --restart=always     --name=instagram-bot     -d     -v /home/gianni/Documenti/Doker/insta-bot/config.js:/app/config.js    socialmanagertools/instagram-bot.js &>/dev/null


Grazie per la disponibilità.

________________________________
Da: Julian Xhokaxhiu <notifications@github.com>
Inviato: giovedì 26 aprile 2018 20:24:04
A: social-manager-tools/instagram-bot.js
Cc: Gianni Savini; Author
Oggetto: Re: [social-manager-tools/instagram-bot.js] [ITA] Problemi nel run del bot v0.7 (branch master) tramite docker (#33)


Non so se sia relativo a Docker. Riesci a copiare e incollare i log per piacere? Come screenshot sono poco utili. Grazie.

**Comment by Jenjo7** [comment]
Certo, allego il file di log e il file config.js; questo è il comando usato per runnare il container:
       sudo docker run --restart=always     --name=instagram-bot     -d     -v /home/gianni/Documenti/Doker/insta-bot/config.js:/app/config.js    socialmanagertools/instagram-bot.js &>/dev/null

Grazie per la disponibilità.


________________________________
Da: Gianni Savini
Inviato: giovedì 26 aprile 2018 22:09:19
A: social-manager-tools/instagram-bot.js
Oggetto: Re: [social-manager-tools/instagram-bot.js] [ITA] Problemi nel run del bot v0.7 (branch master) tramite docker (#33)


Certo, allego il file di log e il file config.js; questo è il comando usato per runnare il container:

       sudo docker run --restart=always     --name=instagram-bot     -d     -v /home/gianni/Documenti/Doker/insta-bot/config.js:/app/config.js    socialmanagertools/instagram-bot.js &>/dev/null


Grazie per la disponibilità.

________________________________
Da: Julian Xhokaxhiu <notifications@github.com>
Inviato: giovedì 26 aprile 2018 20:24:04
A: social-manager-tools/instagram-bot.js
Cc: Gianni Savini; Author
Oggetto: Re: [social-manager-tools/instagram-bot.js] [ITA] Problemi nel run del bot v0.7 (branch master) tramite docker (#33)


Non so se sia relativo a Docker. Riesci a copiare e incollare i log per piacere? Come screenshot sono poco utili. Grazie.

**Comment by ptkdev** [comment]
Try if release v0.7.0 solved this problem

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>
