### ISSUE TITLE
Code Hangs on likemode_competitor_users  >2,7mil follower

### ISSUE THREAD

**Issue by clacetera** [social-manager-tools/instagram-bot.js#34]
### Versions

Replace the values below with your own:

- **Bot Version:**  Branch Master
- **Node Version:** v8.11.2
- **Operating System:** Debian 8 (Docker)
- **Browser:** Google Chrome 64 (puppetes installation headless)

### Actual Behavior

(node:7) UnhandledPromiseRejectionWarning: Error: waiting for selector "main article:nth-child(1) header section ul li:nth-child(2) a" failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/app/node_modules/puppeteer/lib/FrameManager.js:844:60)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### config.js (remember to remove password)
 "bot_mode": "likemode_competitor_users",

  'account': 'xxxxxxx', // without @

**Comment by agoalofalife** [comment]
how will the time I will look and let you know)

**Comment by ptkdev** [comment]
Try with **v0.7.1**, for me work correctly

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>
