### ISSUE TITLE
On a raspberry pi 3 I can't get it to start. 

### ISSUE THREAD

**Issue by chinciusan** [social-manager-tools/instagram-bot.js#37]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.7.0
- **Node Version:** v8.11.2 (Bot require >= 7.6)
- **Operating System:** Raspbian
- **Browser:** Google Chrome 65

### Expected Behavior

Please describe the program's expected behavior.

```
Launch chrome
```

### Actual Behavior

On a raspberry pi 3 I can't get it to start. 
It seems I cannot get it to run chromium. Even if I specify the executable_path (tried both in bot.js and config.js), it always seems to try and run the chromium inside node_modules. 

here's the output error: 
`(node:23577) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/home/pi/Projects/instagram-bot.js/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome: 1: /home/pi/Projects/instagram-bot.js/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome: Syntax error: Unterminated quoted string
`

**note: on a mac it worked exactly as it was supposed to 

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by chinciusan** [comment]
I think it's because my Rasp Pi is not connected to a monitor. 
Is there any way to make it work even if there's no monitor attached to the PI?

**Comment by ptkdev** [comment]
Hi!
Remember 0.7 is in development.
If you don't have monitor try set chrome_headless on true this parameter hide browser

**Comment by chinciusan** [comment]
> If you don't have monitor try set chrome_headless on true this parameter hide browser

I already did that. 

> Remember 0.7 is in development.
Ok. When I'll have the time, I will try to debug it and see how can I make it work and come back with a solution. 
Thanks for your work!

**Comment by ptkdev** [comment]
How you solved?

**Comment by ptkdev** [comment]
Try this:
#### 1. Install chromium v60
- `apt-get install chromium-browser`

#### 2. Install Node v8
1. `curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh `
2. `sudo bash nodesource_setup.sh`
3. `rm nodesource_setup.sh`
4. `sudo apt-get install nodejs`

#### 4. Use raspbian chromium, not the node_modules version
If you use v0.7
- Edit `bot.js` at line ~49 delete if() function to ~60line
- `const browser = await puppeteer.launch({executablePath: '/usr/bin/chromium-browser', headless: config.chrome_headless, args: config.chrome_options});`

If you use v6.1
- Edit `bot.js` at line ~59 and add chrome path:
- `const browser = await puppeteer.launch({executablePath: '/usr/bin/chromium-browser', headless: config.chrome_headless, args: config.chrome_options});`

**Comment by ptkdev** [comment]
Try release [v0.7.0 HOTFIX](https://github.com/social-manager-tools/instagram-bot.js/releases)

**Comment by ptkdev** [comment]
Try release **v0.7.1** for me work correctly

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>

**Comment by chinciusan** [comment]
Yes, 0.7.1 works for me also! 
Thanks!

**Comment by ptkdev** [comment]
Daje (italian slang for "fuck yeah"). Have a nice day :) 

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>
