### ISSUE TITLE
Comment_mode problem

### ISSUE THREAD

**Issue by matteocef** [social-manager-tools/instagram-bot.js#45]
Last ver, Mac Os 10.13
If i put the bot in "comment_mode" i get this:

> (node:21870) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module '.state'
(node:21870) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

other mode works fine. 

Maybe i didn't understand how to put "comment" in the comment session in the config.

```
   "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["i'm super funny"],
        }
    },
```
i don't understand if is this the problem, or other stuff.

**Comment by ptkdev** [comment]
Hi!
Try [this fix](https://github.com/social-manager-tools/instagram-bot.js/archive/master.zip).

**Comment by agoalofalife** [comment]
@matteocef now there is no possibility to see the error
I can fix it later

**Comment by ptkdev** [comment]
@agoaloflife I try fix on release v0.7.2 imho work fine :)

**Comment by matteocef** [comment]
Now i got this problem. And it keep run, always with this problem.

```
[ERROR] comment: like_get_urlpic error Error: Protocol error (Runtime.callFunctionOn): Object reference chain is too long undefined
[INFO] comment: try leave comment
[INFO] comment: bot is unable to comment on this photo
```

**Comment by ptkdev** [comment]
On single photo or all photo?

**Comment by ptkdev** [comment]
This happen with ` puppeteer v1.5` 
1. Please update to release [v0.7.3](https://github.com/social-manager-tools/instagram-bot.js/releases) 
2. Remove `node_modules` 
3. Run `npm install`.

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>
