### ISSUE TITLE
Not liking post

### ISSUE THREAD

**Issue by bianpratama** [social-manager-tools/instagram-bot.js#50]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.7.3
- **Node Version:** v10.4.1
- **Operating System:** Ubuntu 16.04 on Digital Ocean
- **Browser:** Chromium 66.0.3359.181

### Expected Behavior

Please describe the program's expected behavior.

```
When the bot shows info of "try heart like" and "<3", the post should've been liked and showed in mobile app's "Post you've liked".
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
The bot shows info of "try heart like" and "<3". But the post wasn't liked and showed in mobile app's "Post you've liked"
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run `node bot.js`

### config.js (remember to remove password)
```
module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,

    // Instagram Account
    "instagram_username": "kolektif.coffee", // without @
    "instagram_password": "",
    "instagram_hashtag": ["masfotokopi"], //without #
    "instagram_pin": "sms", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [TODO] fdfmode_classic           - follow user from random hashtag and defollow after 1h | 300 follow-defollow/day.
    // [TODO] fdfmode_defollowall       - defollow all your following (not defollow users in whitelist) | 30 defollow/hour.
    "bot_mode": "likemode_superlike",
    "bot_likeday_min": 400,      // work only in likemode_classic
    "bot_likeday_max": 600,      // work only in likemode_classic. In 2018 limit instagram is descreased to 400-600/day :(
    "bot_sleep_night": true,     // if you need stop bot in night
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_fastlike_min": "15",    // min minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 50min)
    "bot_fastlike_max": "20",    // max minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 60min)
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // follow-defollow user/day, work in fdfmode_classic and fdfmode_defollowall
    "bot_userwhitelist": [""],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic and fdfmode_defollowall
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": [],
        }
    },
    "likemode_competitor_users": {
        "account": "", // without @
    },

    // Puppeteer Configs
    "chrome_headless": true,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // LOG
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};
```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Remember if you use superlike mode set:
`bot_fastlike_min` to `50`
`bot_fastlike_max` to `60`
You are in limit of likes, try like from app instagram.

Yep, after release 0.7 bot don't notify correct if not add <3
**But in your case is rate-limit of like is the problem.**

**Comment by bianpratama** [comment]
@ptkdev I still can like posts from Instagram desktop site and mobile app.

I will try to change `bot_fastlike_min` and `bot_fastlike_max` to the ideal setting for superlike mode, will report with the result.

**Comment by ptkdev** [comment]
`Operating System: Ubuntu 16.04 on Digital Ocean`
You use bot on server? Instagram after 2-3h disable your like from servers-ip. Have a list of servers of world and if detect bot on server stop like.

**Comment by bianpratama** [comment]
@ptkdev yes, I use the bot on Digital Ocean server. I think this is related to @LevPasha/Instagram-API-python#350. It seems that Instagram had blocked the cloud servers' IPs.

For the time being, I will run the bot on local machine.

**Comment by ptkdev** [comment]
Yep, problem is cloud server: instagram-bot.js don't solve problem with cloud servers :( 
**Solution is RaspberryPI** on your home lan.

**Comment by bianpratama** [comment]
@ptkdev yea, indeed. Will buy a RaspberryPI then 😉 

Anyway, great bot you've made. I look forward to more updates in the future, good luck 👍

**Comment by ptkdev** [comment]
Has 3 month of life, it is in the initial phase but work. Slowly it is getting better

**Comment by ptkdev** [comment]
v0.7.5 now available

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
