### ISSUE TITLE
Like button selector changed

### ISSUE THREAD

**Issue by redbaron76** [social-manager-tools/instagram-bot.js#55]
On Instagram Website, the CSS selector for LIKE button (heart icon) changed from:
```
main article:nth-child(1) section:nth-child(1) a:nth-child(1)
```
to
```
main article:nth-child(1) section:nth-child(1) button:nth-child(1)
```

Can't pull request atm, sorry.

**Comment by ptkdev** [comment]
I know, this night instagram change selectors.
v0.7.5 coming soon :)

**Comment by ptkdev** [comment]
v0.7.5 now available

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
