### ISSUE TITLE
Failed to launch chrome on Ubuntu 16 version Server

### ISSUE THREAD

**Issue by waseem312** [social-manager-tools/instagram-bot.js#57]
I am getting error when running the Bot on Amazon ec2 Server Ubuntu OS.

(node:19376) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/var/www/html/kingstagram/instagram-bot.js/node_modules/puppeteer/lib/Launcher.js:255:14)
    at ChildProcess.helper.addEventListener (/var/www/html/kingstagram/instagram-bot.js/node_modules/puppeteer/lib/Launcher.js:245:60)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
(node:19376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Please let me know the solution.

**Comment by waseem312** [comment]
Where should i make a change in code to set chrome_headless on true ?

**Comment by ptkdev** [comment]
I write this: set `chrome_headless` on `true` in config.js file
You are set `config.js` file or is empty?

**Comment by waseem312** [comment]
Thanks @ptkdev .Its working Now !

**Comment by ptkdev** [comment]
Yeah! 💯 

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
