### ISSUE TITLE
Run on VPS - CentOS 7

### ISSUE THREAD

**Issue by nalex88** [social-manager-tools/instagram-bot.js#60]
I have installed your script on remote VPS server (CentOS 7), It is possible continuously put "Like" (likemode_classic) without ban for many days.
Thanks

**Comment by ptkdev** [comment]
Nope, instagram check if like is put from vps/cloud server. After 7-12h bot stop add like and instagram ban server (not account). See #50 or LevPasha/Instagram-API-python#350

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
