### ISSUE TITLE
 instagram no have a crash - what does it mean?

### ISSUE THREAD

**Issue by afedkina1024** [social-manager-tools/instagram-bot.js#68]
### Versions

Replace the values below with your own:

- **Bot Version:** 0.8.2
- **Node Version:** v8.11.1 (Bot require >= 7.6)
- **Operating System:** windows10
- **Browser:** Google Chrome 64

### Expected Behavior

To log in and start liking photos.

### Actual Behavior

In the chromium window the bot login, enters pin and does nothing more. 
In the command line the following text appears: 

[INFO] utils: Bot is updated! :D
[INFO] login: loading...
[INFO] login: open_loginpage
[INFO] login: set_username
[INFO] login: set_password
[INFO] login: submit
[INFO] login: checkerrors
[INFO] login: password is correct
[INFO] login: login_status is 1
[INFO] twofa: instagram request pin (bad location)?
[INFO] twofa: yes, instagram require security pin... You can not pass!!! (cit.)
[INFO] twofa: status location: 1
[INFO] twofa: twofa (location)
[WARNING] twofa: please insert pin in loginpin.txt, you have 50-60 seconds for that.. (tic... tac... tic... tac... tic...)
[INFO] twofa: readpin
[INFO] twofa: submit
[INFO] twofa: pin is ok
[INFO] twofa: **instagram no have a crash**

I do not undersand what does the last message mean. Is there anyting wrong with the account or the instagram website? Without using bot it works normally.

### Steps to Reproduce

1. Run bot
2. enter pin to loginpin.txt if asked

.
### config.js 
```

module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "ardalionovaekaterina", // without @
    "instagram_password": "",
    "instagram_hashtag": ["design", "instapic", "funny", "healthy"], //without #
    "instagram_pin": "email", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [TODO] fdfmode_classic           - follow user from random hashtag and defollow after 1h | 300 follow-defollow/day.
    // [TODO] fdfmode_defollowall       - defollow all your following (not defollow users in whitelist) | 30 defollow/hour.
    "bot_mode": "likemode_realistic",
    "bot_likeday_min": 100,      // work only in likemode_classic
    "bot_likeday_max": 200,      // work only in likemode_classic. In 2018 limit instagram is 1000/day
    "bot_sleep_night": true,     // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_fastlike_min": "1",    // min minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 50min)
    "bot_fastlike_max": "2",    // max minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 60min)
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 300,        // follow-defollow user/day, work in fdfmode_classic and fdfmode_defollowall
    "bot_userwhitelist": [""],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic and fdfmode_defollowall
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": [],
        }
    },
    "likemode_competitor_users": {
        "account": "", // without @
    },

    // Puppeteer Configs
    "chrome_headless": false,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // LOG
    "pin_path":"./loginpin.txt",
    "log_path":"./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path":"./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};

**Comment by ptkdev** [comment]
Hi, 2FA at moment work randomly. This is [instagram website bug](https://github.com/social-manager-tools/instagram-bot.js/issues/48#issuecomment-396088139), if you try login on instagram website with your browser (not bot) login don't work (pin error, but is correct). At moment solution is:
- disable 2FA
- start bot
- after login, enable 2FA

Duplicate bug, see #48 

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>

**Comment by afedkina1024** [comment]
Thank you for the fast reply. The problem is that **I do not use** two-factor authentication in my account.  I don't know why instagram sends that security code to my email, it didn't do it before and I never asked for that. It says there was  suspicious login attempt, and this message appears every time I log in. Anyway the bot deals correctly with that pincode, there is a message in the command prompt that "**pin is ok**" but after that nothing happens in browser, just showing the account start page and I don't know if the bot is working or not. As I understand **instagram no have a crash** message means there is a problem in the Instagam website, right?

**Comment by ptkdev** [comment]
@afedkina1024 i see log: `[INFO] twofa: twofa (location)` location sms pin flow happen when you use bot on vps/server/cloud or different connection than your home ip.

If you run bot on server/cloud/vps instagram have list of ip and ban new ip of server/vps/cloud after login and bot don't work correctly. But not ban your account. 

[Raspberry PI 3](https://github.com/social-manager-tools/instagram-bot.js/blob/master/INSTALL.md) is raccomanded than vps :)

See #50 or LevPasha/Instagram-API-python#350

**Comment by afedkina1024** [comment]
Thanks a lot for your help. Actually I am not using any server at the moment, just running the bot from my home computer. Earlier I launched another script from https://github.com/mgp25/Instagram-API to post likes and used a proxy server for that. It was working normally for a while, then stopped because of that suspicious login attempt error I mentioned before.  And does your bot allow working with a proxy server?

**Comment by ptkdev** [comment]
@afedkina1024  At moment proxy is not available. You not use vps/server? Is very strange if bot ask sms location. Try [Social Manager Tools](https://socialmanagertools.ptkdev.io/)
