### ISSUE TITLE
Pass config file path as parameter

### ISSUE THREAD

**Issue by lecoueyl** [social-manager-tools/instagram-bot.js#71]
This is a feature request.
I can create Pull request if needed

### Versions

Replace the values below with your own:

- **Bot Version:** v0.8.2
- **Node Version:** v10.9 (Bot require >= 7.6)
- **Operating System:** Ubuntu 14.04
- **Browser:** Google Chrome 64

### Expected Behavior

Please describe the program's expected behavior.

```
Add a --config option to pass a desired config file as a parameter.
This able to execute two instances (for example) with the same script to run the bot on different account.
Use the config/config.js as default or execute an other instance with npm run start -- --config="config/account-name.js"
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
The script use a direct javascript config file to run (const config = require ("./config");)
Need to duplicate the script if needed to use it for two or more account
```

**Comment by ptkdev** [comment]
Hi! 
If you want create pull request :)

**Comment by lecoueyl** [comment]
@ptkdev I made a new PR 
https://github.com/social-manager-tools/instagram-bot.js/pull/73
let ne know what you think!
