### ISSUE TITLE
follow forom list

### ISSUE THREAD

**Issue by FaRzad-845** [social-manager-tools/instagram-bot.js#75]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.8.2
- **Node Version:** v8.9 (Bot require >= 7.6)
- **Operating System:** win 10
- **Browser:** Google Chrome 64

i have a list of usernames and i want to follow them, how can i do this ?

**Comment by ptkdev** [comment]
This features not is Available at moment

**Comment by FaRzad-845** [comment]
can you tell me the routes of project ?
mayb i should do it myself 
special thanks

**Comment by FaRzad-845** [comment]
`await this.bot.waitForSelector("?????");
        let button = await this.bot.$("???????");`
can you help me what can i put instead of ????? to get the follow button

**Comment by ptkdev** [comment]
This is css selector, see source code of instagram page for get correct value. 
Find css selector into `class="xxx"` and replate it instead of ?????

**Comment by FaRzad-845** [comment]
thanks ... !
