### ISSUE TITLE
fdfmode_classic not working

### ISSUE THREAD

**Issue by AleTassi** [social-manager-tools/instagram-bot.js#77]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.8.2
- **Node Version:** v8.11 (Bot require >= 7.6)
- **Operating System:** Windows 10
- **Browser:** Chromium 64

### Expected Behavior

fdfmode_classic mode not working, sending errors.

### Actual Behavior

[INFO] utils: Bot is updated! :D
[INFO] login: loading...
[INFO] login: open_loginpage
[INFO] login: set_username
[INFO] login: set_password
[INFO] login: submit
[INFO] login: checkerrors
[INFO] login: password is correct
[INFO] login: login_status is 1
[INFO] twofa: instagram request pin (bad location)?
[INFO] twofa: no, try second verify
[INFO] twofa: status location: 0
[INFO] twofa: instagram request pin (2fa enabled)?
[INFO] twofa: no, bot is at work (started)... Wait...
[INFO] twofa: starting current mode
[INFO] twofa: status: 0
(node:11836) UnhandledPromiseRejectionWarning: TypeError: strategy(...).start is not a function
    at switch_mode (C:\Users\Tassi\Desktop\workspace\instagram-bot.js-0.8.2\node_modules\instagrambotlib\lib.js:84:52)
    at module.exports.start (C:\Users\Tassi\Desktop\workspace\instagram-bot.js-0.8.2\node_modules\instagrambotlib\lib.js:113:23)
    at <anonymous>
(node:11836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Steps to Reproduce

1. Just set "fdfmode_classic" as mode.

### config.js (remember to remove password)

module.exports = {
    // InstagramBot.js Configs
    "debug": true,
    "login": true,
    "ui": false, // only for social-manager-tools

    // Instagram Account
    "instagram_username": "username", // without @
    "instagram_password": "password",
    "instagram_hashtag": ["ragazzo", "ragazzoitaliano", "italianguy", "mestesso", "stanco"], //without #
    "instagram_pin": "email", //method to receive pin (email or sms)

    // BOT Configs
    // [WORK] likemode_classic          - select random hashtag from config list and like 1 random photo (of last 20) | 400-600 like/day.
    // [WORK] likemode_realistic        - select random hashtag from config list, like fast 10-12 photo and sleep 15-20min. Sleep at night
    // [WORK] likemode_superlike        - select random hashtag from config list and like 3 random photo of same user | 400-600 like/day.
    // [WORK] likemode_competitor_users - select account, select random followers, like 10-12 photo and sleep 15-20min.
    // [WORK] comment_mode              - leave a comment under the photo via hashtag.
    // [TODO] fdfmode_classic           - follow user from random hashtag and defollow after 1h | 300 follow-defollow/day.
    // [TODO] fdfmode_defollowall       - defollow all your following (not defollow users in whitelist) | 30 defollow/hour.
    "bot_mode": "fdfmode_classic",
    "bot_likeday_min": 800,      // work only in likemode_classic
    "bot_likeday_max": 900,      // work only in likemode_classic. In 2018 limit instagram is 1000/day
    "bot_sleep_night": false,     // if you need stop bot in night 
    "bot_start_sleep": "7:00",   // sleep from 00:00 to 7:00 am, work in likemode_realistic, comment_mode, likemode_superlike and likemode_competitor_users
    "bot_fastlike_min": "5",    // min minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 50min)
    "bot_fastlike_max": "10",    // max minutes of sleep after like 10-12 photo, work in likemode_realistic and likemode_superlike (superlike add 3 like/user, set 60min)
    "bot_superlike_n": 3,        // superlike number of likes for user
    "bot_followday": 500,        // follow-defollow user/day, work in fdfmode_classic and fdfmode_defollowall
    "bot_userwhitelist": ["a.tassi.a"],   // usernames without @ | don't defollow this users on follow-defollow mode, work in fdfmode_classic and fdfmode_defollowall
    "comment_mode": {
        "comments": {
            "type": "array",
            "source": ["Wow :D", "Carino ;D", "Mi piace!", "Wei!", "Mi piaci!"],
        }
    },
    "likemode_competitor_users": {
        "account": "", // without @
    },

    // Puppeteer Configs
    "chrome_headless": false,
    "chrome_options": ["--disable-gpu", "--no-sandbox", "--window-size=1920x1080"],
    "executable_path": "", // example for Mac OS: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

    // LOG
    "pin_path":"./loginpin.txt",
    "log_path":"./logs/debug.log",
    "logerr_path":"./logs/errors.log",
    "screenshot_path":"./logs/screenshot/",
    "log": {
        "drivers": ["console"], // slack or console
        "screenshot": false,  // disable or enable screenshot in logs folder
        "channels": {
            "console": "",
            "slack": {
                "webhook": ""
            }
        }
    }
};

**Comment by ptkdev** [comment]
Hi! At moment fdf mode aren't available in release. Is market "test". 

fdf will be Available in 0.9.0 version in september

**Comment by ptkdev** [comment]
Available in release **v0.9.0**

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
