### ISSUE TITLE
Config.js Guide

### ISSUE THREAD

**Issue by focamonca** [social-manager-tools/instagram-bot.js#83]
That's not a BUG or an issue relatoed to the code but I can't figure out how to customize properly config.js file.

Where do I set the bot mode I want to use?
Where do I set values to customize other modes rather than realistic?
Where do I create the comment array?
Is it possible to make it like, comment and follow in the same mode?

thankis for the answer
I hope you create a guide about it

**Comment by ptkdev** [comment]
![Image of Yaktocat](https://preview.ibb.co/fD86S9/Schermata_del_2018_09_13_09_44_08.png)

This version of bot is "hard to use", Try [Social Manager Tools](https://socialmanagertools.ptkdev.io/) for Windows, Mac and Linux. GUI Version of bot.

**Comment by focamonca** [comment]
thanks
